### ISSUE TITLE
atomic tests and hooks

### ISSUE THREAD

**Issue by eliasmalik** [FAC10/week2-TimeForce#38]
You have a reset function in your tests because some of your functions change global variables. Aside from the problem of relying on global variables, be aware that you can use test hooks that run before and after each test to do this clean up for you and prevent you having to call `reset` manually after each test. See the docs [here](http://api.qunitjs.com/QUnit.module/)

```js
QUnit.module('Name', { beforeEach: resetScript }, function (assert) {
  // blah
});
```

These are often used to acheive tests that are atomic; that is, tests that are completely independent of each other, and can run in any order. This is generally what you should be aiming for.

**Comment by samatar26** [comment]
I had come across that yesterday, but couldn't understand from the documentation how to implement this within the module. Thanks a bunch for showing me how :+1:
